### ISSUE TITLE
node-red-node-wemo error

### ISSUE THREAD

**Issue by tribbles3** [node-red/node-red-nodes#616]
## Which node are you reporting an issue on?

node-red-node-wemo v0.1.15

### What happens?

node-red crashes after running for about 24 hours with the following error:

[red] Uncaught Exception:
Error: connect ETIMEOUT 10.0.0.70:49153
at Object._errnoException (util.js:992:11)
at _exceptionWithHostPort (util.js:1014:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

### Please tell us about your environment:

- [ ] Node-RED version: v0.18.7
- [ ] node.js version: v8.11.3
- [ ] Platform/OS: Windows 7

**Comment by hardillb** [comment]
This is because your wemo device is either offline or doesn't have a stable IP address. So when the node trys to contact it the connection fails with a timeout.

Unfortunately because it's a asynchronous error it can't easily be caught, and it's going to be difficult to work where it's coming from. Are you using the status node or just the control nodes?

**Comment by tribbles3** [comment]
Just the control node.

**Comment by hardillb** [comment]
OK, I think I've found the problem. I can probably stop it crashing, but the fact it's hitting this problem does imply that your WeMo devices are falling off the network.

I'm busy today, but I'll try and get a fix to test tomorrow.

**Comment by tribbles3** [comment]
Okay, thanks. :)

I know that one of my WEMO devices does loose its connection from time to time but it reconnects after a bit.

**Comment by hardillb** [comment]
There is a test fix available to test here: https://www.hardill.me.uk/node-red-node-wemo-0.1.16.tgz

you should be able to install that by going into the `~/.node-red` and running `npm install /path/to/node-red-node-wemo-0.1.16.tgz`

**Comment by tribbles3** [comment]
Installed. I will let you know how it goes, thanks!

**Comment by tribbles3** [comment]
No crashes as of yet. Will it still throw an error to the Catch node if it loses connection?

**Comment by hardillb** [comment]
No, but it will print to the console ,

**Comment by dceejay** [comment]
Is this all good now ?

**Comment by tribbles3** [comment]
Actually it crashed again yesterday with the same error. :(

**Comment by hardillb** [comment]
Are you sure it was the same timeout error? If you still have a logs please add the error here

**Comment by tribbles3** [comment]
Unfortunately I no longer have the console output but I will be sure to capture it when/if it happens again.

**Comment by tribbles3** [comment]
It crashed again so I was able to check the error and it is the same as before.

[red] Uncaught Exception:
Error: connect ETIMEOUT 10.0.0.70:49153
at Object._errnoException (util.js:992:11)
at _exceptionWithHostPort (util.js:1014:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by hardillb** [comment]
Looks like I may have missed one instance. I've pushed a new test version to the same place as last time.

**Comment by tribbles3** [comment]
Happy to say that I have not had any wemo related crashes since the update on Jan 19. Thanks.

**Comment by dceejay** [comment]
OK - we'll close this now then... 
can re-open if necessary.

**Comment by hardillb** [comment]
Nope, I'll open a pull request with my changes and we can close it when it's merged. I'll try and get to it at the weekend (assuming I don't get really bored at the office this week)

**Comment by tribbles3** [comment]
Strange thing... I just created a new node-red setup and added node-red-node-wemo via the pallet manager and I am getting the following error.

[red] Uncaught Exception:
Error: connect ETIMEOUT 10.0.0.70:49153
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)

For this setup I am using:

node.js: v12.16.1 (newer version than used previously)
node-red: v1.0.3 (new version than used previously)

**Comment by hardillb** [comment]
Not sure what happened it looks like I have an outstanding change set to push with the last set up timeout catches. I'll push them now.

**Comment by tribbles3** [comment]
Looks like that worked, no errors for 2 days. Thanks.

**Comment by hardillb** [comment]
Nothing has changed in the code pushed to npm yet, we need to merge those changes and publish still

**Comment by tribbles3** [comment]
Then it must be that there just hasn't been a disconnect episode since I restarted node-red. :) If/When I receive an error, I will just wait until you have pushed the code to npm.

**Comment by tribbles3** [comment]
Just wanted to follow up and let you know that node-red is still crashing with the same error using version 0.1.17

I had removed the wemo devices but recently decided to give it a try again but no joy.
